### ISSUE TITLE
Problem with expect statements in specs

### ISSUE THREAD

**Issue by MitulMistry** [learn-co-curriculum/js-ajax-callbacks-lab#2]
My code was functioning properly in the browser, but the specs kept giving: _TypeError: 'undefined' is not a function (evaluating 'verbs.includes(expectedVerb)')_ and _TypeError: 'undefined' is not a function (evaluating 'nouns.includes(expectedNoun)')_

It seemed like the problem was with the includes matcher and after doing some research, I changed the statements as follows and it now seems to work:

16: expect(verbs.includes(expectedVerb)).toBe(true)
-Changed to: expect(verbs).toContain(expectedVerb);

30: expect(nouns.includes(expectedNoun)).toBe(true)
-Change to: expect(nouns).toContain(expectedNoun);

**Comment by AnnJohn** [comment]
Thanks @MitulMistry we're going to be reviewing our JS curriculum in the next week and will update this lab based on your issue then.

**Comment by pletcher** [comment]
Hi @MitulMistry, what browser are you using? [`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) should be defined in any modern browser except IE. Have you tried running the specs in Chrome or Firefox?

**Comment by pletcher** [comment]
Hi @MitulMistry, I'm going to close this issue for now. If it comes up again, feel free to reopen!
