### ISSUE TITLE
Submit Error 

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-ajax-callbacks-lab#3]
I am getting this error when running learn submit:

`error: src refspec master does not match any. (Git::GitExecuteError)`

I manually pushed to my own github after all of my tests passed.

**Comment by AnnJohn** [comment]
Hi @aenser sorry about this and this looks like a technical bug. Could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug. 

Thanks!
