### ISSUE TITLE
Where is SpecRunner.html?

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/js-ajax-callbacks-lab#4]
The README references `SpecRunner.html`, but I don't see the file anywhere in the history. Am I going crazy?

cc @vicfriedman

**Comment by victhevenot** [comment]
@pletcher nope - definitely no `SpecRunner.html`. In an ideal world, students would be able to run the jasmine tests by entering `jasmine`, but currently none of our labs support that. I guess in the meantime take that line out of the readme?

**Comment by pletcher** [comment]
What would you think about getting students used to writing `npm test` to
run their tests? I can rewrite this lab to demo.

On Mon, Feb 29, 2016 at 1:28 PM, Victoria Friedman <notifications@github.com

**Comment by victhevenot** [comment]
totally! we need to be able to support running `learn -b` to get the lights to change, but students don't ever get to actually learn how to run jasmine tests, for any app they would be building. i love the idea how having both

**Comment by pletcher** [comment]
Cool. So the thinking behind `npm test` is that it _should_ make `learn`'s
job easier. Most JavaScript tests don't actually need a browser these days
(except for very specific things), they just need a browser-like
environment. I'll open a PR here.

On Mon, Feb 29, 2016 at 5:12 PM, Victoria Friedman <notifications@github.com

**Comment by victhevenot** [comment]
@pletcher should we remove the reference to `SpecRunner.html` in the readme?

**Comment by pletcher** [comment]
Yeah, it looks like that gets created (and destroyed) on the fly by the test gem.
