### ISSUE TITLE
learn submit requires master branch

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/js-ajax-callbacks-lab#8]
the initial fork via learn open was for the cd/first-draft branch. instead of the normal master branch. had to manually 'git push' to catch up with the fork and then go to the github page to change the head fork to the master branch in order for the lab to respond. before i did this manually this was the error for reference. 

Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
/Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/Users/pjwickwire/Development/code/js-ajax-callbacks-lab-v-000/.git' '--work-tree=/Users/pjwickwire/Development/code/js-ajax-callbacks-lab-v-000' push 'origin' 'master'  2>&1:error: src refspec master does not match any. (Git::GitExecuteError)
error: failed to push some refs to 'git@github.com:pajamaw/js-ajax-callbacks-lab-v-000.git'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/git-1.3.0/lib/git/lib.rb:742:in`push'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/git-1.3.0/lib/git/base.rb:329:in `push'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:123:in`block in push!'
    from /Users/pjwickwire/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
    from /Users/pjwickwire/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in`block in catch'
    from /Users/pjwickwire/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in `catch'
    from /Users/pjwickwire/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:32:in`catch'
    from /Users/pjwickwire/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:122:in`push!'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:23:in `commit_and_push'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:46:in`commit_and_push!'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:22:in `create'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:6:in`create'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/gems/learn-submit-1.1.7/bin/learn-submit:15:in `<top (required)>'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/bin/learn-submit:23:in`load'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/bin/learn-submit:23:in `<main>'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`eval'
    from /Users/pjwickwire/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by AnnJohn** [comment]
thanks; just updated the student repo to default to master branch and deleted the other irrelevant branches in there.

**Comment by pajamaw** [comment]
no problem!
