### ISSUE TITLE
Specs run `includes` function which causes `learn` to fail

### ISSUE THREAD

**Issue by mendelB** [learn-co-curriculum/js-ajax-callbacks-lab#9]
@AnnJohn @PeterBell @pletcher #7 
Some students had an issue where their tests worked in the browser but failed in console. turns out `includes` as opposed to `indexOf` is not supported in many platforms.

**Comment by PeterBell** [comment]
Hey @mendelB great catch - thanks! LGTM, but would love :eyes: from @pletcher just to check it out

**Comment by pletcher** [comment]
Fixed with #10
